version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.20.2-neo"
replacements:
  name: "WaveyCapes"
  id: "waveycapes"
  version: "1.4.1"
  relocationpackage: "dev.tr7zw.waveycapes"
  modrinthid: kYuIpRLv
  curseforgeid: 521594
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - publishNeo
  - modrinth
  - curseforge
  - versionless
rootProject:
  template: "."
subProjects:
  WCFabric:
    template: "Fabric"
    replacements:
      dependencies: '
      modImplementation "curse.maven:morebanners-515000:4575797"
      
      modCompileOnly "maven.modrinth:ears:1.4.6+fabric-1.20.2"

      modCompileOnly "curse.maven:minecraftcapes-mod-359836:4763650"

      inc project(":WCVersionless")
      '
  WCForge:
    template: "Forge"
    replacements:
      dependencies: '
      modCompileOnly "curse.maven:minecraftcapes-mod-359836:4562670"

      inc project(":WCVersionless")

      forgeRuntimeLibrary project(":WCVersionless")
      '
  WCNeo:
    template: "Neo"
    replacements:
      dependencies: '

      inc project(":WCVersionless")

      forgeRuntimeLibrary project(":WCVersionless")
      '
  WCVersionless:
    template: "Versionless"
    replacements:
      dependencies: '
      compileOnly "com.google.code.gson:gson:2.10.1"

      compileOnly "org.apache.logging.log4j:log4j-core:2.20.0"
      '